version: "3.7"
services:

  nginx:
      image: nginx:1.16.1
      ports:
          - 80:80
      volumes:
          - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
          - ./front_end/dist:/usr/share/nginx/html
          - ./front_end/assets:/usr/share/nginx/assets
      depends_on:
          - flask-app

  flask-app:
      build:
          context: ./services/web
          dockerfile: Dockerfile
      command:  python manage.py run -h 0.0.0.0
      volumes:
          - ./services/web/:/usr/src/app/
          - ./services/uploaded_files:/usr/local/uploaded_files
          - /Volumes/Documents/Household:/usr/local/household
      ports:
          - 5000:5000
